title: Štěpán Jiří Karásek
description: About me, games, videos, Mastodon, and blog
baseurl: ""
url: "https://sjk.eu"

markdown: kramdown
permalink: /blog/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
