title: Štěpán Jiří Karásek
description: About me, games, videos, Mastodon, and blog

baseurl: "/stepankarasek.github.io"
url: "https://stepanjiri.github.io"

markdown: kramdown
permalink: /blog/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
